apiVersion: apps/v1
kind: Deployment
metadata:
  name: sir-lancebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sir-lancebot
  template:
    metadata:
      labels:
        app: sir-lancebot
    spec:
      containers:
      - name: sir-lancebot
        image: ghcr.io/python-discord/sir-lancebot:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: sir-lancebot-env
