apiVersion: apps/v1
kind: Deployment
metadata:
  name: sir-lancebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sir-lancebot
  template:
    metadata:
      labels:
        app: sir-lancebot
    spec:
      containers:
      - name: sir-lancebot
        image: ghcr.io/python-discord/sir-lancebot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
          limits:
            cpu: 20m
            memory: 100Mi
        envFrom:
        - secretRef:
            name: sir-lancebot-env
        - secretRef:
            name: redis-credentials
