apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-config-env
data:
  # Domain to access bitwarden by
  DOMAIN: "https://bitwarden.pythondiscord.com"

  # Password hint must be sent to an email when this is false.
  # When it's true, it'll be shown right on the page.
  SHOW_PASSWORD_HINT: "false"

  # Admins only, please!
  SIGNUPS_ALLOWED: "false"

  # Used for LiveSync
  WEBSOCKET_ENABLED: "true"
