apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: bitwardenrs/server-postgresql:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: bitwarden-secret-env
            - configMapRef:
                name: bitwarden-config-env
