apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox-forms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox-forms
  template:
    metadata:
      labels:
        app: snekbox-forms
    spec:
      initContainers:
        - name: init-service
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args: 
          - >
            wget https://image1.com -O /tmp/img1.png
            wget https://image2.com -O /tmp/img2.png
            wget https://image3.com -O /tmp/img3.png
          volumeMounts:
            - name: snekbox-forms-images
              mountPath: /tmp/
      containers:
        - name: snekbox-forms
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: snekbox-forms-user-base-volume
              mountPath: /snekbox/user_base
            - name: snekbox-forms-images
              mountPath: /snekbox/forms-images
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >-
                    PYTHONUSERBASE=/snekbox/user_base
                    pip install --user --upgrade
                    pip
                    pillow==10.0.0
                    opencv-python-headless==4.8.0.74
      volumes:
        - name: snekbox-forms-user-base-volume
          emptyDir: {}
        - name: snekbox-forms-images
          emptyDir: {}
