apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox-forms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox-forms
  template:
    metadata:
      labels:
        app: snekbox-forms
    spec:
      containers:
        - name: snekbox-forms
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: snekbox-forms-user-base-volume
              mountPath: /snekbox/user_base
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >-
                    PYTHONUSERBASE=/snekbox/user_base
                    pip install --user --upgrade
                    pip
                    pillow==10.0.0
                    opencv-python-headless==4.8.0.74
      volumes:
        - name: snekbox-forms-user-base-volume
          emptyDir: {}
