apiVersion: v1
kind: ConfigMap
metadata:
  name: hastebin-init
data:
  init.sh: |
    #!/bin/bash

    # Clone the repo
    git clone https://github.com/seejohnrun/haste-server.git
    cd haste-server

    # Install and start
    npm install

    set -e

    # Generate the config file from the environment
    node docker-entrypoint.js > config.js

    # Start Hastebin
    npm start
