apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: ghcr.io/python-discord/bot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - secretRef:
            name: bot-env
        - secretRef:
            name: sentry-env
        - secretRef:
            name: redis-credentials
