apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: default
data:
  redis.conf: |
    # Store all commands used and replay on server startup
    appendonly yes

    # Set working directory
    dir /data

    # Set a memory maximum
    maxmemory 1gb
