# Exporter for taking statistics on our PostgreSQL instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              cpu: 20m
              memory: 50Mi
          ports:
            - containerPort: 9187
          env:
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: /opt/python-discord/queries/queries.yaml
          envFrom:
            - secretRef:
                name: postgres-exporter-env
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /opt/python-discord/queries
            name: queries
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      volumes:
      - configMap:
          defaultMode: 420
          name: postgres-exporter-queries
        name: queries
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
