# Exporter for taking statistics on our PostgreSQL instance
#
# Required secrets:
#   - postgres-exporter-env
#
#       Should contain environment variables listed at https://github.com/wrouesnel/postgres_exporter but most
#       notably should contain DATA_SOURCE_NAME containing a postgresql connection URI.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              cpu: 20m
              memory: 50Mi
          ports:
            - containerPort: 9187
          envFrom:
            - secretRef:
                name: postgres-exporter-env
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
